spring:
  application:
    name: inventory-module

  datasource:
    url: jdbc:postgresql://localhost:5432/inventory_db
    username: postgres
    password: Ather1010
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          time_zone: UTC

  flyway:
    enabled: false

server:
  port: 9090

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace